files:
  - source: /docs/**/*.md
    ignore:
      - '*.zh_CN.md'
      - '*.es.md'
      - '*.sv.md'
      - '*.fr.md'
      - index.en.md
    translation: /%original_path%/%file_name%.%two_letters_code%.%file_extension%
